// SPDX-License-Identifier: GPL-3.0-or-later
const $=s=>document.querySelector(s),root=$('#game'),dialog=$('#dialog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let socket,game=null,connected=false,token='',retry=0,retryTimer,selected=new Set(),hintIndex=0,sound=false,audioContext,clockOffset=0,noticeTimer;
try{token=sessionStorage.getItem('fengxun.ddz.token')||'';sound=localStorage.getItem('fengxun.ddz.sound')==='true'}catch{}
const codeFromURL=new URL(location.href).searchParams.get('room')||'';
const btn=(action,label,cls='',disabled=false)=>`<button data-action="${action}" class="${cls}" ${disabled?'disabled':''}>${label}</button>`;
const suitNames=['黑桃','红心','梅花','方块'];
function info(id){const rank=id<52?id%13+3:id-36,suit=id<52?Math.floor(id/13):4;return {rank,suit,label:rank<11?String(rank):({11:'J',12:'Q',13:'K',14:'A',15:'2',16:'小王',17:'大王'})[rank],symbol:['♠','♥','♣','♦',''][suit],red:suit===1||suit===3||id===53}}
function card(id,interactive=false){const c=info(id),name=(c.suit<4?suitNames[c.suit]:'')+c.label;return `<${interactive?'button':'span'} class="card ${c.red?'red':''} ${c.suit===4?'joker':''} ${selected.has(id)&&interactive?'selected':''}" ${interactive?`data-card="${id}" aria-label="${name}" aria-pressed="${selected.has(id)}" ${!canSelect()?'disabled':''}`:`role="img" aria-label="${name}"`}><span class="corner"><b>${c.label}</b><i>${c.symbol}</i></span><span class="pip" aria-hidden="true">${c.symbol||'王'}</span></${interactive?'button':'span'}>`}
const pile=ids=>(ids||[]).map(id=>card(id)).join('');
function canSelect(){return connected&&game?.phase==='playing'&&game.turn===game.you&&!game.players[game.you].auto}
function role(seat){return game.landlord<0?'待定':seat===game.landlord?'地主':'农民'}
function portrait(index,cls=''){return `<span class="portrait ${cls}" style="--face:${index*50}%" aria-hidden="true"></span>`}
function opponent(seat,side){const p=game.players[seat];if(!p)return `<aside class="opponent ${side}"><div class="empty-seat">等一位好友</div></aside>`;const face=p.name==='晚晴'?0:p.name==='松风'?1:side==='left'?0:1;return `<aside class="opponent ${side} ${game.turn===seat&&['playing','bidding'].includes(game.phase)?'active':''}">${portrait(face)}<p class="player-name">${esc(p.name)}<small>${p.bot?'电脑':p.online?'在线':'暂时离线'} · ${role(seat)}</small></p><span class="card-count">${p.count} 张</span>${p.say?`<span class="said">${esc(p.say)}</span>`:''}</aside>`}
function lobby(){return `<section class="lobby"><div class="lobby-panel"><h2>来，打两把</h2><p>一个人练习，或邀两位好友同桌。</p>${btn('practice','人机对战','primary practice',!connected)}<div class="divider" aria-hidden="true"><i></i></div><div class="friend-entry">${btn('create','创建好友房','outline',!connected)}<form id="join"><label class="sr-only" for="room-code">输入房间码</label><input id="room-code" placeholder="输入房间码" value="${esc(codeFromURL.slice(0,6))}" maxlength="6" pattern="[A-Za-z2-9]{6}" autocomplete="off" autocapitalize="characters" required><button class="outline" ${!connected?'disabled':''}>加入房间</button></form></div><p class="connection ${connected?'online':''}" role="status">${connected?'服务已连接':'正在连接牌桌……'}</p></div><footer>GPL-3.0 开源版 · 原作 <a href="https://github.com/palemoky/fight-the-landlord" target="_blank" rel="noopener">palemoky</a> <span>｜</span> <a href="https://github.com/davidse63/fight-the-landlord" target="_blank" rel="noopener">源码</a></footer></section>`}
function waiting(){const mine=game.players[game.you];return `<section class="waiting"><div class="lobby-panel"><h2>好友同桌</h2><p>房间码 <strong class="room-code">${esc(game.code)}</strong></p><div class="seat-list">${[0,1,2].map(i=>{const p=game.players[i];return `<div>${p?portrait(i):'<span class="empty-seat">空位</span>'}<strong>${p?esc(i===game.you?'你':p.name):'等待好友'}</strong><small>${p?p.ready?'已准备':p.online?'尚未准备':'暂时离线':'分享房间码邀请加入'}</small></div>`}).join('')}</div><p class="waiting-note">三人到齐并准备后开局。房间码仅分享给想邀请的人。</p><div class="waiting-actions">${btn('share','复制邀请链接','outline')}${btn('ready',mine.ready?'取消准备':'准备好了','primary',!connected)}${btn('leave','离开房间','text-button')}</div><p class="connection ${connected?'online':''}">${connected?'服务已连接':'连接中断，正在恢复……'}</p></div></section>`}
function status(){if(!connected)return '连接中断，正在恢复牌局……';if(game.phase==='ended')return '本局结束';const p=game.players[game.turn];if(game.players[game.you].auto)return '正在托管 · 可随时接回手牌';if(game.phase==='bidding')return game.turn===game.you?(game.grab?'轮到你抢地主':'轮到你叫地主'):`等待${p.bot?'电脑':p.name}${game.grab?'抢':'叫'}地主`;return game.turn===game.you?(game.mustPlay?'新一轮，由你领出':'轮到你出牌'):`等待${p.bot?'电脑':p.name}出牌`}
function actions(){const me=game.players[game.you];if(me.auto)return btn('manual','接回手牌','primary',!connected);const turn=connected&&game.turn===game.you;if(game.phase==='bidding')return btn('no-bid',game.grab?'不抢':'不叫','outline',!turn)+btn('bid',game.grab?'抢地主':'叫地主','primary',!turn);return btn('pass','不出','outline',!turn||game.mustPlay)+btn('hint','提示','outline',!turn)+btn('play','出牌','primary',!turn||selected.size===0)}
function ending(){const won=(game.you===game.landlord)===(game.winner===game.landlord);return `<article class="ending"><h2>${won?'这局，配合得漂亮':'好牌局，下把再来'}</h2><p>${game.winner===game.landlord?'地主获胜':'农民获胜'} · ${game.multiplier} 倍${game.spring?' · 春天':''}</p><div class="result-list">${game.players.map((p,i)=>`<div><strong>${i===game.you?'你':esc(p.name)}<small>${role(i)}</small></strong><b class="${p.score>0?'positive':''}">${p.score>0?'+':''}${p.score} 分</b><div class="remaining">${pile(p.hand)}</div></div>`).join('')}</div><p class="result-note">本局娱乐计分，不涉及金钱。</p><div class="ending-actions">${btn('ready',game.players[game.you].ready?'等待其他玩家准备':'再来一局','primary',!connected||game.players[game.you].ready)}${btn('record','回看牌局','outline')}${btn('leave','返回大厅','text-button')}</div></article>`}
function table(){if(game.phase==='waiting')return waiting();if(game.phase==='ended')return `<section class="table finished">${ending()}</section>`;const left=(game.you+2)%3,right=(game.you+1)%3;return `<section class="table"><div class="table-meta"><div class="bottom-cards">${game.landlord>=0?pile(game.bottom):'<span class="back-card"></span>'.repeat(3)}</div><p>${game.landlord>=0?'底牌':'底牌待揭晓'} · 倍数 <strong>${game.multiplier}</strong></p></div>${opponent(left,'left')}${opponent(right,'right')}<div class="centre-play"><div class="played-cards">${pile(game.target)}</div><p>${game.target?.length?esc(game.players[game.lastSeat].name)+' · '+esc(game.players[game.lastSeat].say):game.phase==='bidding'?'叫地主后揭晓底牌':game.mustPlay?'新一轮':'等待出牌'}</p></div><div class="turn-message" role="status">${status()} <span data-countdown></span></div><div class="play-actions">${actions()}</div><div class="own-player">${portrait(2)}<p>你 · ${role(game.you)}</p></div><div class="hand-region"><div class="hand" role="group" aria-label="你的手牌" style="--count:${game.hand.length}">${(game.hand||[]).map(id=>card(id,true)).join('')}</div><div class="hand-caption"><span>${role(game.you)} · ${game.hand.length} 张${selected.size?` · 已选 ${selected.size} 张`:''}</span>${btn('clear','取消选择','text-button',!selected.size)}</div></div><nav class="table-tools" aria-label="牌桌工具">${btn('record','牌局记录','text-button')}${btn('auto',game.players[game.you].auto?'托管中':'托管','text-button',!connected)}${!game.practice?btn('share','房间 '+esc(game.code),'text-button'):''}${btn('leave','离桌','text-button')}</nav></section>`}
function render(){const focused=document.activeElement?.dataset?.card;root.innerHTML=game?table():lobby();updateSound();clock();if(focused)root.querySelector(`[data-card="${focused}"]`)?.focus({preventScroll:true})}
function say(message){clearTimeout(noticeTimer);$('#notice').textContent=message;$('#notice').classList.add('show');noticeTimer=setTimeout(()=>$('#notice').classList.remove('show'),5000)}
function emit(type,extra={}){if(!connected||socket.readyState!==WebSocket.OPEN){say('连接正在恢复，请稍候');return};socket.send(JSON.stringify({type,version:game?.version||0,...extra}))}
function connect(){clearTimeout(retryTimer);const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);socket=ws;ws.onopen=()=>ws.send(JSON.stringify({type:'hello',token}));ws.onmessage=event=>{if(socket!==ws)return;let msg;try{msg=JSON.parse(event.data)}catch{return};if(msg.type==='welcome'){token=msg.token;try{sessionStorage.setItem('fengxun.ddz.token',token)}catch{}connected=true;retry=0;return};if(msg.type==='state'){const before=game;game=msg.game;clockOffset=game?game.serverTime-Date.now():0;if(!game||before?.version!==game.version){selected.clear();hintIndex=0};if(game&&before&&game.history?.length>before.history?.length)tone();render();if(msg.message)say(msg.message);return};if(msg.type==='hint'&&game?.version===msg.version){selected=new Set(msg.cards||[]);hintIndex++;render();say(msg.message);return};if(msg.type==='error')say(msg.message)};ws.onclose=()=>{if(socket!==ws)return;connected=false;render();retryTimer=setTimeout(connect,Math.min(10000,1000*2**Math.min(retry++,4)))};ws.onerror=()=>ws.close()}
function clock(){const label=$('[data-countdown]');if(!label||!game)return;const seconds=Math.max(0,Math.ceil((game.deadline-Date.now()-clockOffset)/1000));label.textContent=game.deadline>0?`${seconds} 秒`:game.practice?'不限时':''}
function updateSound(){const b=$('[data-action="sound"]');b.setAttribute('aria-pressed',String(sound));b.setAttribute('aria-label',sound?'关闭音效':'开启音效')}
function tone(){if(!sound)return;try{audioContext??=new AudioContext();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.type='sine';o.frequency.value=440;g.gain.setValueAtTime(.045,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.09);o.start();o.stop(audioContext.currentTime+.1)}catch{}}
function openDialog(title,body){$('#dialog-body').innerHTML=`<h2 id="dialog-title">${title}</h2>${body}`;dialog.showModal()}
function help(){openDialog('这桌怎么玩',`<p>三人一副 54 张牌，每人先拿 17 张。先叫地主，再轮流抢；无人叫则重新随机洗牌。地主拿三张底牌并先出，任一农民先出完，两位农民一起获胜。</p><h3>出牌与跟牌</h3><p>牌从小到大：3—10、J、Q、K、A、2、小王、大王。跟牌要同牌型、同长度且更大；炸弹可压普通牌型，王炸最大。两家不出，最后出牌者重新领出。</p><ul><li>单张、对子、三张、三带一、三带一对</li><li>顺子（至少 5 张）、连对（至少 3 对）：不含 2 和王</li><li>飞机（至少两个连续三张）：可不带，或每组三张带一张／一对，主体不含 2 和王；单翅膀可含对子</li><li>四带二（两张，可成对）、四带两对（两个不同点数的对子）</li><li>炸弹、王炸</li></ul><h3>操作与计分</h3><p>点选手牌，再点“出牌”；再次点牌可取消。“提示”只选择牌，不会替你出牌，多点可换一组。好友对局出牌 30 秒，叫地主 20 秒；超时由电脑代出。人机练习在你操作时不限时。</p><p>每次抢地主、炸弹、王炸翻倍。地主胜且农民均未出牌，或农民胜且地主只出过一次，计春天翻倍。地主得失为两倍底分，农民各一倍，仅作本局娱乐计分。</p><p>托管可随时取消。连接中断后会自动尝试恢复；服务器重启或房间过期后需重新开局。</p><p><a href="https://github.com/davidse63/fight-the-landlord" target="_blank" rel="noopener">本版源码与 GPL-3.0 许可</a> · 原作 palemoky。网页版新增牌桌、房间会话和完整出牌提示；人机策略使用 DouZero，服务不可用时回退规则策略。</p>`)}
document.addEventListener('click',async e=>{const cardButton=e.target.closest('[data-card]');if(cardButton&&canSelect()){const id=Number(cardButton.dataset.card);selected.has(id)?selected.delete(id):selected.add(id);render();return};const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='close'){dialog.close();return}if(a==='help'){help();return}if(a==='sound'){sound=!sound;try{localStorage.setItem('fengxun.ddz.sound',String(sound))}catch{}updateSound();tone();return}if(a==='clear'){selected.clear();render();return}
 if(a==='record'){if(!game)return;openDialog('牌局记录',`<ol class="record">${(game.history||[]).map(h=>`<li><strong>${h.seat<0?'牌桌':esc(game.players[h.seat]?.name)}</strong><span>${esc(h.text)}${h.cards?.length?' · '+h.cards.map(id=>esc(info(id).label)).join(' '):''}</span></li>`).join('')}</ol>`);return}
 if(a==='share'){const url=`${location.origin}/?room=${game.code}`;try{await navigator.clipboard.writeText(url);say('邀请链接已复制，发给两位好友即可')}catch{openDialog('邀请好友',`<p>房间码：<strong>${esc(game.code)}</strong></p><label for="share-url">复制这个链接</label><input id="share-url" value="${esc(url)}" readonly>`)}return}
 if(a==='leave'){if(!game)return;openDialog('离开这张牌桌？',`<p>${game.practice?'本局人机练习将结束。':game.phase==='playing'||game.phase==='bidding'?'对局会由电脑代打接手，你将返回大厅。':'你将退出房间并返回大厅。'}</p><div class="dialog-actions">${btn('close','继续玩','outline')}${btn('confirm-leave','确认离桌','primary')}</div>`);return}
 if(a==='confirm-leave'){dialog.close();emit('leave');return}if(a==='manual'){emit('auto',{auto:false});return}if(a==='auto'){emit('auto',{auto:!game.players[game.you].auto});return}if(a==='bid'||a==='no-bid'){emit('bid',{bid:a==='bid'});return}if(a==='hint'){emit('hint',{index:hintIndex});return}if(a==='play'){emit('play',{cards:[...selected]});return}if(['practice','create','pass','ready'].includes(a))emit(a)
});
document.addEventListener('submit',e=>{if(e.target.id==='join'){e.preventDefault();emit('join',{code:$('#room-code').value.trim().toUpperCase()})}});
document.addEventListener('keydown',e=>{if(!e.target.dataset.card||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const all=[...root.querySelectorAll('[data-card]')],i=all.indexOf(e.target),next=all[i+(e.key==='ArrowRight'?1:-1)];next?.focus()});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
window.addEventListener('online',()=>{if(!connected)connect()});window.addEventListener('pagehide',()=>{clearTimeout(retryTimer);const old=socket;socket=null;old?.close()});window.addEventListener('pageshow',e=>{if(e.persisted)connect()});setInterval(clock,500);setInterval(()=>{if(connected)emit('ping')},25000);render();connect();
